// курсовая работа/userprofile_vue/src/components/FileUpload.vue
<!-- FileUpload.vue -->
<template>
  <div>
    <label for="file-upload">Загрузите файл:</label>
    <input
      id="file-upload"
      type="file"
      @change="onFileChange"
      @keydown.enter.prevent="triggerClick"
      ref="fileInput"
    >
    <!-- Сообщение о статусе загрузки -->
    <div
      v-if="statusMessage"
      aria-live="polite"
      class="status-message visually-hidden"
    >{{ statusMessage }}</div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const emit = defineEmits(['uploaded', 'failed']);
const fileInput = ref(null);
const statusMessage = ref('');

const onFileChange = (event) => {
  const file = event.target.files[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = () => {
      emit('uploaded', reader.result);
      statusMessage.value = 'Файл успешно загружен.';
      clearStatusMessage();
    };
    reader.onerror = (error) => {
      emit('failed', error);
      console.error('Ошибка при чтении файла:', error);
      statusMessage.value = 'Ошибка при загрузке файла.';
      clearStatusMessage();
    };
    reader.readAsDataURL(file);
  } else {
    statusMessage.value = 'Файл не выбран.';
    clearStatusMessage();
  }
};

const triggerClick = () => {
  fileInput.value.click();
};

const clearStatusMessage = () => {
  setTimeout(() => {
    statusMessage.value = '';
  }, 5000);
};
</script>

<style>
.visually-hidden {
  position: absolute;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  height: 1px;
  width: 1px;
  white-space: nowrap;
}
</style>

// курсовая работа/userprofile_react/src/components/FileUpload.jsx
import React, { useRef } from 'react';

const FileUpload = ({ onUploaded, onFailed }) => {
  const fileInputRef = useRef(null);

  const onFileChange = (event) => {
    const file = event.target.files[0];
    const statusMessageElement = document.getElementById('file-upload-status');
    if (file) {
      const reader = new FileReader();
      reader.onload = () => {
        onUploaded(reader.result);
        statusMessageElement.textContent = 'Файл успешно загружен.';
      };
      reader.onerror = (error) => {
        onFailed(error);
        console.error('Ошибка при чтении файла:', error);
        statusMessageElement.textContent = 'Ошибка при загрузке файла.';
      };
      reader.readAsDataURL(file);
    } else {
      statusMessageElement.textContent = 'Файл не выбран.';
    }
    setTimeout(() => {
      statusMessageElement.textContent = '';
    }, 5000);
  };

  const triggerClick = () => {
    fileInputRef.current.click();
  };

  return (
    <div>
      <label htmlFor="file-upload">Загрузите файл:</label>
      <input
        id="file-upload"
        type="file"
        onChange={onFileChange}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            triggerClick();
          }
        }}
        ref={fileInputRef}
      />
      <div
        id="file-upload-status"
        className="visually-hidden"
        aria-live="polite"
      ></div>
    </div>
  );
};

export default FileUpload;
